config/routes.rb
Lcbeyond::Application.routes.draw do
  
  root "welcome#index"

    resources :products
    resources :stores

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  require 'open-uri'
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  	page = params[:page] || 1
  	@products = JSON.parse(open("http://lcboapi.com/products?where=has_limited_time_offer&order=limited_time_offer_savings_in_cents.desc&per_page=10&page=#{page}").read)
  	@clearance = JSON.parse(open("http://lcboapi.com/products?where=has_clearance_sale&order=clearance_sale_savings_in_cents.desc&per_page=30&page=#{page}").read)
  end

  def show
  	@product = JSON.parse(open("http://lcboapi.com/products/#{params[:id]}").read)['result']
  end

  def update
  
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def index
  	@stores = JSON.parse(open("http://lcboapi.com/stores/").read)
  end

  def show
  	@store = JSON.parse(open("http://lcboapi.com/stores/#params[:id]").read)['result']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@dataset = JSON.parse(open("http://lcboapi.com/datasets/928").read)['result'] #converts into hash
  	@featureid = @dataset['product_ids'].sample
  	@feature = JSON.parse(open("http://lcboapi.com/products/#{@featureid}").read)['result']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	

end

app/helpers/stores_helper.rb
module StoresHelper
	
	def open(store)
		@store = store
		time = Time.new
		week = ["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]
		current_day = week[time.wday]
		current_time  = (time.hour*60)+time.min
		if @store["#{current_day}_open"] < current_time && @store["#{current_day}_close"] > current_time
				return true
			else
				return false
		end
	end

	def timeleft(store)
		@store = store
		time = Time.new
		week = ["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]
		current_day = week[time.wday]
		current_time  = (time.hour*60)+time.min
		minutesleft = @store["#{current_day}_close"] - current_time
		distance_of_time_in_words(time, time + minutesleft.minutes)
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lcbeyond</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h2> CHEAP HOOCH </h2>
<% @products['result'].each do |product| %>
<div>
	<%= link_to product['name'], product_path(product['id']) %>
</div>
<div>normal price of this product: <%= number_to_currency(product['regular_price_in_cents']/100) %></div>
<div>
	savings on this item: <%= number_to_currency(product['limited_time_offer_savings_in_cents']/100) %>
</div>
<div>
	savings % = <%=  (product['limited_time_offer_savings_in_cents'].to_f / product['regular_price_in_cents'].to_f) %>
</div>
<div>
	savings per ml: <%= number_to_currency( product['limited_time_offer_savings_in_cents'].to_f/product['volume_in_milliliters'].to_f ) %>
</div>
<div>
	savings per ml of alcohol: <%= ( product['limited_time_offer_savings_in_cents'].to_f/(product['alcohol_content']/100 *product['volume_in_milliliters']).to_f ) %>
</div>
<% end %>
<%= @products['pager']['current_page'] %> of <%= @products['pager']['final_page'] %> pages

<%= link_to 'prev page', products_path( page: @products['pager']['current_page']-1 ) unless @products['pager']['current_page'] < 1 %>
<%= link_to 'next page', products_path( page: @products['pager']['current_page']+1 ) unless @products['pager']['current_page'] >= @products['pager']['final_page']  %>



<%= link_to "Home", root_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<%= image_tag @product['image_url'] %>
<%= @product['name'] %>

<%= link_to "Back", products_path %>

app/views/stores/index.html.erb
<% @stores['result'].each do |store| %>
<div>
	<%= link_to store['name'], "http://www.lcbo.com/lcbo-ear/jsp/storeinfo.jsp?language=EN&STORE=#{store['id']}" %>
	<% if open(store) %>
		<div>Closes in <%= timeleft(store) %></div>
	<% else  %>
		<div>Closed</div>
	<% end  %>
</div>
<% end %>

app/views/stores/show.html.erb
<h1>Stores#show</h1>
<p>Find me in app/views/stores/show.html.erb</p>

app/views/welcome/index.html.erb
<h1>why not try a...<h1>
	<div>
	<%= image_tag @feature['image_thumb_url'] %>
	<%= @feature['name'] %>
	<%= number_to_currency(@feature['price_in_cents']/100) %>
	<%= @feature['id'] %>
</div>

	<%= link_to "Products", products_path %>
	<%= link_to "Stores", stores_path %>